=== Balachandar380/HackathonProject/v2.4.0/plugins/com.vitesco.farm.editor_2.3.0/APP-INF/app-ui.dtd
<!ELEMENT application-ui (title, editor-mode?, single-launch-on-port?, look-and-feel-class-name?, actions?, menus?, toolbar?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT editor-mode (#PCDATA)>
<!ELEMENT single-launch-on-port (#PCDATA)>
<!ELEMENT look-and-feel-class-name (#PCDATA)>

<!ELEMENT actions (action*)>
<!ELEMENT action (action-command, command-class, name?, short-description?, long-description?, small-icon?, accelerator?, mnemonic?)>
<!ATTLIST action enabled (true | false) "true">
<!ELEMENT action-command    (#PCDATA)>
<!ELEMENT command-class     (#PCDATA)>
<!ELEMENT name              (#PCDATA)>
<!ELEMENT short-description (#PCDATA)>
<!ELEMENT long-description  (#PCDATA)>
<!ELEMENT small-icon        (#PCDATA)>
<!ELEMENT accelerator       (#PCDATA)>
<!ELEMENT mnemonic          (#PCDATA)>
<!ATTLIST name              istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
<!ATTLIST short-description istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
<!ATTLIST long-description  istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
<!ATTLIST small-icon        istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
<!ATTLIST accelerator       istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
<!ATTLIST mnemonic          istring CDATA #IMPLIED  layout-variable CDATA #IMPLIED>
	
<!ELEMENT menus (menu*)>
<!ELEMENT menu ((menu|menu-separator)*)>
<!ATTLIST menu	title              CDATA #IMPLIED
				istring            CDATA #IMPLIED
				action-command-ref CDATA #IMPLIED>
				
<!ELEMENT menu-separator EMPTY>

<!ELEMENT toolbar ((button|button-separator)*)>
<!ELEMENT button EMPTY>
<!ATTLIST button action-command-ref CDATA #REQUIRED>
<!ELEMENT button-separator EMPTY>

=== Balachandar380/HackathonProject/v2.4.0/plugins/com.vitesco.farm.editor_2.3.0/APP-INF/app-ui_OEM.xml
<?xml version="1.0"?>
<!DOCTYPE application-ui SYSTEM "app-ui.dtd">

<application-ui>
    <title>FARM Editor</title>
    <editor-mode>OEM</editor-mode>
    <single-launch-on-port>11666</single-launch-on-port>
    <!--
        <look-and-feel-class-name>com.sun.java.swing.plaf.windows.WindowsLookAndFeel</look-and-feel-class-name>
    -->
    <!-- maps Swing action by their action command name to application commands -->
    <!-- following action commands will be fired by the frame (if available) -->
    <!-- (they cannot be disabled) -->
    <!--
         ApplicationUI.Frame.windowOpened
         ApplicationUI.Frame.windowClosing
         ApplicationUI.Frame.windowClosed
         ApplicationUI.Frame.windowIconified
         ApplicationUI.Frame.windowDeiconified
         ApplicationUI.Frame.windowActivated
         ApplicationUI.Frame.windowDeactivated
     -->
    <actions>
        <action>
            <action-command>ApplicationUI.Frame.windowClosing</action-command>
            <command-class>com.vitesco.farm.command.ExitEditorCommand</command-class>
        </action>

        <action enabled="true">
            <action-command>Exit</action-command>
            <command-class>com.vitesco.farm.command.ExitEditorCommand</command-class>
            <name>Exit</name>
        </action>

        <action enabled="true">
            <action-command>CheckModified</action-command>
            <command-class>com.vitesco.farm.command.CheckModifiedCommand</command-class>
        </action>

        <action enabled="true">
            <action-command>ApplicationUI.Toolbar.floating</action-command>
            <command-class>com.vitesco.farm.swing.command.DefaultToolbarFloatingCommand</command-class>
            <name istring="ToolbarFloating.name"/>
        </action>

        <action enabled="true">
            <action-command>ShowDisclaimer</action-command>
            <command-class>com.vitesco.farm.command.ShowDisclaimerCommand</command-class>
            <name istring="ShowDisclaimer.name"/>
            <small-icon>/icons/general/disclaimer.png</small-icon>
        </action>

				<action enabled="true">
            <action-command>ValidateLinkDescXML</action-command>
            <command-class>com.vitesco.farm.command.ValidateLinkDescXMLCommand</command-class>
            <name istring="ValidateLinkDescXML.name"/>            
        </action>

        <action enabled="true">
            <action-command>About</action-command>
            <command-class>com.vitesco.farm.command.AboutCommand</command-class>
            <name istring="About.name"/>
            <short-description istring="About.short-description"/>
            <small-icon>/icons/farm/info.png</small-icon>
            <accelerator istring="About.accelerator"/>
        </action>

        <action enabled="true">
            <action-command>HelpTopics</action-command>
            <command-class>com.vitesco.farm.swing.command.DefaultHelpCommand</command-class>
            <name istring="HelpTopics.name"/>
            <small-icon>/icons/farm/question-mark.png</small-icon>
            <accelerator istring="HelpTopics.accelerator"/>
        </action>
        
        

        <action>
            <action-command>Find</action-command>
            <command-class>com.vitesco.farm.command.FindInViewCommand</command-class>
            <name istring="Find.name"/>
            <short-description istring="Find.short-description"/>
            <long-description istring="Find.long-description"/>
            <small-icon>/icons/general/Find16.gif</small-icon>
            <accelerator istring="Find.accelerator"/>
        </action>

        <action enabled="false">
            <action-command>Undo</action-command>
            <command-class>com.vitesco.farm.command.UndoCommand</command-class>
            <name istring="Undo.name"/>
            <short-description istring="Undo.short-description"/>
            <long-description istring="Undo.long-description"/>
            <small-icon>/icons/general/Undo16.gif</small-icon>
            <accelerator istring="Undo.accelerator"/>
        </action>

        <!-- base command for reading FARM data -->
        <action enabled="true">
            <action-command>ImportFarm</action-command>
            <command-class>com.vitesco.farm.command.ImportFarmCommand</command-class>
        </action>

        <!-- base command for exporting FARM data -->
        <action enabled="true">
            <action-command>ExportFarm</action-command>
            <command-class>com.vitesco.farm.command.ExportFarmCommand</command-class>
        </action>

        <action enabled="false">
            <action-command>ImportFarmExchange</action-command>
            <command-class>com.vitesco.farm.command.ImportFarmExchangeCommand</command-class>
            <name istring="ImportFarmExchange.name"/>
            <short-description istring="ImportFarmExchange.short-description"/>
            <long-description istring="ImportFarmExchange.long-description"/>
            <small-icon>/icons/general/Import16.gif</small-icon>
            <accelerator istring="ImportFarmExchange.accelerator"/>
            <mnemonic istring="ImportFarmExchange.mnemonic"/>
        </action>

        <action enabled="false">
            <action-command>ExportFarmExchange</action-command>
            <command-class>com.vitesco.farm.command.ExportFarmExchangeCommand</command-class>
            <name istring="ExportFarmExchange.name"/>
            <short-description istring="ExportFarmExchange.short-description"/>
            <long-description istring="ExportFarmExchange.long-description"/>
            <small-icon>/icons/general/Export16.gif</small-icon>
            <accelerator istring="ExportFarmExchange.accelerator"/>
            <mnemonic istring="ExportFarmExchange.mnemonic"/>
        </action>
        
        <action enabled="false">
            <action-command>ExportFarmStatistics</action-command>
            <command-class>com.vitesco.farm.command.ExportFarmStatisticsCommand</command-class>
            <name istring="ExportFarmStatistics.name"/>
            <short-description istring="ExportFarmStatistics.short-description"/>
            <long-description istring="ExportFarmStatistics.long-description"/>
            <small-icon>/icons/general/Export16.gif</small-icon>
            <accelerator istring="ExportFarmStatistics.accelerator"/>
            <mnemonic istring="ExportFarmStatistics.mnemonic"/>
        </action>
        
        <action enabled="true">
            <action-command>File.Open</action-command>
            <command-class>com.vitesco.farm.command.FileOpenCommand</command-class>
            <name istring="File.Open.name"/>
            <short-description istring="File.Open.short-description"/>
            <long-description istring="File.Open.long-description"/>
            <small-icon>/icons/general/Open16.gif</small-icon>
            <accelerator istring="File.Open.accelerator"/>
            <mnemonic istring="File.Open.mnemonic"/>
        </action>

        <action enabled="false">
            <action-command>File.Save</action-command>
            <command-class>com.vitesco.farm.command.FileSaveCommand</command-class>
            <name istring="File.Save.name"/>
            <short-description istring="File.Save.short-description"/>
            <long-description istring="File.Save.long-description"/>
            <small-icon>/icons/farm/save.png</small-icon>
            <accelerator istring="File.Save.accelerator"/>
            <mnemonic istring="File.Save.mnemonic"/>
        </action>

        <action enabled="false">
            <action-command>File.SaveAs</action-command>
            <command-class>com.vitesco.farm.command.FileSaveAsCommand</command-class>
            <name istring="File.SaveAs.name"/>
            <short-description istring="File.SaveAs.short-description"/>
            <long-description istring="File.SaveAs.long-description"/>
            <small-icon>/icons/farm/save-as.png</small-icon>
            <accelerator istring="File.SaveAs.accelerator"/>
            <mnemonic istring="File.SaveAs.mnemonic"/>
        </action>
	<action enabled="false">
            <action-command>File.ExportAs</action-command>
            <command-class>com.vitesco.farm.command.FileExportAsCommand</command-class>
            <name istring="File.ExportAs.name"/>
            <short-description istring="File.ExportAs.short-description"/>
            <long-description istring="File.ExportAs.long-description"/>
            <small-icon>/icons/farm/save-as.png</small-icon>
            <accelerator istring="File.ExportAs.accelerator"/>
            <mnemonic istring="File.ExportAs.mnemonic"/>
        </action>

        <action enabled="false">
            <action-command>File.SaveSpreadsheetViewsAs</action-command>
            <command-class>com.vitesco.farm.command.FileSaveSpreadsheetViewsAsCommand</command-class>
            <name istring="File.SaveSpreadsheetViewsAs.name"/>
            <short-description istring="File.SaveSpreadsheetViewsAs.short-description"/>
            <long-description istring="File.SaveSpreadsheetViewsAs.long-description"/>
            <small-icon>/icons/farm/save-as.png</small-icon>
            <accelerator istring="File.SaveSpreadsheetViewsAs.accelerator"/>
            <mnemonic istring="File.SaveSpreadsheetViewsAs.mnemonic"/>
        </action>

        <action enabled="false">
            <action-command>File.Open2ndFile</action-command>
            <command-class>com.vitesco.farm.command.FileOpen2ndCommand</command-class>
            <name istring="File.Open2ndFile.name"/>
            <short-description istring="File.Open2ndFile.short-description"/>
            <long-description istring="File.Open2ndFile.long-description"/>
