<?xml version="1.0"?>

<!-- do not edit this doctype, the launcher will be confused otherwise -->
<!DOCTYPE application [
	<!ELEMENT application (title, locale, splash, main-class, args)>
	<!ELEMENT title       (#PCDATA)>
	<!ELEMENT splash      (#PCDATA)>
	<!ELEMENT locale      (#PCDATA)>
	<!ELEMENT main-class  (#PCDATA)>
	<!ELEMENT args        (arg*)>
	<!ELEMENT arg         (#PCDATA)>
]>

<!-- leave unneeded elements empty                             -->
<!-- resource paths are relative to APP-INF                    -->
<!-- arg paths are relative to the location of launch.jar      -->
<!-- locale code is <<language>>[_<<country>>], e.g. de, en_US -->

<application>
	<title>FARM Editor</title>
	<locale>en_US</locale>
	<splash>images/FRED.png</splash>
	<main-class>com.vitesco.farm.ui.FarmEditor</main-class>
	<args>
	</args>
</application>